name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.11.0

      - name: Get variables
        id: get_vars
        run: |
          echo '::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)'
          echo '::set-output name=DATE::$(date +'%D')'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run build
        run: pnpm build
        env:
          CI: false

      - name: Bump manifest version
        run: node .github/actions/bump-manifest-version.js
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}

      - name: Push manifest change
        uses: EndBug/add-and-commit@v8
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          message: "chore: bump manifest version to ${{ github.ref_name }}"

      - name: Update tag ref
        uses: EndBug/latest-tag@latest
        with:
          ref: ${{ github.ref_name }}

      - name: Bundle files
        run: |
          mkdir -p ./temp/screencapture
          mkdir -p ./temp/screencapture/game
          mkdir -p ./temp/screencapture/game/nui
          cp ./{README.md,LICENSE,fxmanifest.lua} ./temp/screencapture
          cp -r ./game/dist ./temp/screencapture/game/dist
          cp -r ./game/nui/dist ./temp/screencapture/game/nui/dist
          cd ./temp && zip -r ../screencapture.zip ./screencapture

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        id: auto_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "${{ env.RELEASE_VERSION }}"
          prerelease: false
          files: screencapture.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}